services:
  frontend:
    build:
      context: ./bodegabox-web
      dockerfile: Dockerfile.dev
    volumes:
      - ./bodegabox-web:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./bodegabox-rest
      dockerfile: Dockerfile.dev
    volumes:
      - ./bodegabox-rest:/app
      - /go/pkg/mod
      - bodegabox-images:/app/data/images
    command: air
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ENV: ${ENV}
      GIN_MODE: debug
    depends_on:
      - db

  db:
    volumes:
      - bodegabox-data:/var/lib/postgresql/data

volumes:
  bodegabox-data:
  bodegabox-images: